import type { Metadata } from "next";
import "./globals.css";
import { onest, inter } from "./fonts" 
import Header from "@/components/task2/headers/header";
import Footer from "@/components/task2/footer/footer";
import Breadcrumbs from "@/components/breadcrumbs";

import {Provider} from "./provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body

          className={`${onest.variable} ${inter.variable} antialiased `}
        >  
          <Provider>
            <div className="bg-[#D4D4D8]">
              <Header />
              <Breadcrumbs/>
            
              {children}
              <Footer />
            </div> 
          </Provider>  
        </body>
    </html>
  );
}

